package vitniksys.backend.model.enums;

public enum Reason
{
    NA, FALLA_EN_CIERRES_BOTONES_ACCESORIOS, FALLAS_DE_CONFECCIÓN, FALLAS_EN_TELA_DESTEÑIMIENTO, MAL_ENVASADO_ETIQUETADO,
    ENVÍO_EQUIVOCADO, MANCHADO, CAMBIO_DE_TALLE, NO_SATISFACE_CALCE, NO_SATISFACE_PRODUCTO, PRODUCTO_MAL_PEDIDO, PRODUCTO_DIFIERE_CON_TABLA_MEDIDAS,
    SEGUNDA_FACTOR_PROCESO_RECICLAJE, TALLER_FACTOR_PROCESO_RECICLAJE, LAVADERO_FACTOR_PROCESO_RECICLAJE, OTROS;
}